travis:
  secure:
    BINSTAR_TOKEN: 0Mv4qYp2mnpS8Ap4rHRtsUeAxaI/5a3AiUSKtN/jpH2MRselPn3YOYLhDFt/ZqvKy+NZvQWrBe7v3qjJeed6n3y+jshScMvK+4YaiEXH0w8cSVP53QenC1S5PX8HxdsSpym6us7B5ooogB2YoIe5YgcZ5l2RwzgZS4ZvNhHTHa6IeReGtfF350oFjpnGhRVbvnIDEaa9KJ1ju+3e/wDgAMSm6c3x33tNQoGD65S8Tj7WWm4UpeSTbn4oGTsOw2vHAkUwVHFkR9YDa+JgtUtfzUZlZFcshK97HIzFPQULJHDyw1flMmU00N2bxtE1v3cJIeNIWXXCNXX35YQ52s4PI2TKhGFPUqArEqWDKwJIIaxdsvosHJtNfbogncSPmZL0jjSD92c2IAIFRS2zEJ47iJ2XG1a5+3Goz/apIzVe/hQ+AZxMUraokc9hg0NK/yDTv5Ngu+NsE2BH4J19VAw7xMVYl5WPenb4BG9tyjMCOhJU9p3qd5LHj8Zn7Lad7nuKOftxgWiSatRGHathdZbK5QE+ee7t0qZtU0PpR0OtoXU4tDKLaU8ZN/MLoJZWFbd3aBZSV/IXDjHBeBpo8yMVELviih7liNMJiWezrFMJDCV69BcZOoAI0KJMetqLkukkLC54ZDWKndOOu3lDxe5VRZPCEadfphZB8yyC9kEWs7M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
